### ISSUE TITLE
Which version of Keras should be used?

### ISSUE THREAD

**Issue by heng2j** [dvazquezcvc/keras_fcn#3]
Hi David,

We are trying to run the train.py as described. With Python 2.7 and Keras 1.2.0 in Tensorflow 1.2.1.

But encountered the following error due to generator_queue has been changed to GeneratorEnqueuer.

**Log:**
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    from callbacks.callbacks_factory import Callbacks_Factory
  File "/scratch/<User>/keras_zoo/keras_zoo/callbacks/callbacks_factory.py", line 7, in <module>
    from callbacks import (History_plot, Jacc_new, Save_results,
  File "/scratch/<User>/keras_zoo/keras_zoo/callbacks/callbacks.py", line 6, in <module>
    from keras.engine.training import GeneratorEnqueuer
ImportError: cannot import name GeneratorEnqueuer

However, if we used Keras 2.0.2. the names from other packages has been changed as well.

**Log:**
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 15, in <module>
    from models.model_factory import Model_Factory
  File "/scratch/<User>/keras_zoo/keras_zoo/models/model_factory.py", line 6, in <module>
    from keras.utils.visualize_util import plot
ImportError: No module named visualize_util

To full reproduce the experiment, do you mind to suggest which dependencies should we use?

Thank you,
Heng

**Comment by MADONOKOUKI** [comment]
Did you upgrade tensorflow or Keras?
I had a same problem, but by upgrading, I can fix it.
try `pip3 install keras --upgrade`
